/** TESTNET */
export const SEPOLIA_NFT_FACTORY_ADDRESS = '0x061b0604e6A0c6CDAe32Fd5de3Cdfb93F8Cb12bc'
export const SEPOLIA_NFT_MARKETPLACE_ADDRESS = '0xb0F8bc832B3154fE8e0AaE498cDF5a5fFC7150A2'
export const SEPOLIA_NFT_ROYALTIES_ADDRESS = '0x17685381cf40e6F362eAa139CB93C5C3B6B0cbF3'

export const POLYGON_AMOY_NFT_FACTORY_ADDRESS = ''
export const POLYGON_AMOY_NFT_MARKETPLACE_ADDRESS = ''
export const POLYGON_AMOY_NFT_ROYALTIES_ADDRESS = ''

/** MAINNET */
export const MAINNET_NFT_FACTORY_ADDRESS = ''
export const MAINNET_NFT_MARKETPLACE_ADDRESS = ''
export const MAINNET_NFT_ROYALTIES_ADDRESS = ''


export const POLYGON_NFT_FACTORY_ADDRESS = ''
export const POLYGON_NFT_MARKETPLACE_ADDRESS = ''
export const POLYGON_NFT_ROYALTIES_ADDRESS = ''



