@shippo_token = {{$dotenv SHIPPO_API_KEY}}

# Variables générales
@api_base_url = https://api.goshippo.com
@content_type = application/json

# Variables adresse pour validation
@name = IRA
@organization = 
@address_line_1 = 62 rue des forges
@address_line_2 = 
@city_locality = Plélan-le-grand
@state_province = Bretagne
@postal_code = 35380
@country_code = FR

# Variables pour les colis (tableaux d'artistes)
# Unités communes
@distance_unit = cm
@mass_unit = kg
@parcel_template = 
@parcel_metadata = Tableau d'artiste

# Petit tableau
@petit_length = 40
@petit_width = 5
@petit_height = 30
@petit_weight = 1.5

# Moyen tableau (dimensions actuelles)
@moyen_length = 90
@moyen_width = 8
@moyen_height = 70
@moyen_weight = 3

# Grand tableau
@grand_length = 150
@grand_width = 12
@grand_height = 120
@grand_weight = 7

# Dimensions actives (changer cette section pour utiliser petit/moyen/grand)
@parcel_length = {{grand_length}}
@parcel_width = {{grand_width}}
@parcel_height = {{grand_height}}
@parcel_weight = {{grand_weight}}

### SHIPPO - API V2 - VALIDATE ADDRESS

GET {{api_base_url}}/v2/addresses/validate?name={{name}}&organization={{organization}}&address_line_1={{address_line_1}}&address_line_2={{address_line_2}}&city_locality={{city_locality}}&state_province={{state_province}}&postal_code={{postal_code}}&country_code={{country_code}}
Authorization: ShippoToken {{shippo_token}}

### SHIPPO - API V2 - CREATE ADDRESS

POST {{api_base_url}}/v2/addresses
Content-Type: {{content_type}}
Authorization: ShippoToken {{shippo_token}}

{
  "name": "{{name}}",
  "organization": "{{organization}}",
  "email": "gb.palmera.it@gmail.com",
  "phone": "+33685908630",
  "address_line_1": "{{address_line_1}}",
  "address_line_2": "{{address_line_2}}",
  "city_locality": "{{city_locality}}",
  "state_province": "{{state_province}}",
  "postal_code": "{{postal_code}}",
  "country_code": "{{country_code}}",
  "address_type": "residential"
}


### SHIPPO - API V2 - GET ALL ADDRESSES

GET {{api_base_url}}/v2/addresses
Authorization: ShippoToken {{shippo_token}}

### SHIPPO - API V2 - DELETE ADDRESS

DELETE {{api_base_url}}/v2/addresses/3ff7fbfe6207474ca2274c0d0f7a3947
Authorization: ShippoToken {{shippo_token}}


##############################################################################################
##############################################################################################
#############################    PARCELS    ##################################################
##############################################################################################
##############################################################################################

### SHIPPO - CREATE PARCEL

POST {{api_base_url}}/parcels/
Content-Type: {{content_type}}
Authorization: ShippoToken {{shippo_token}}

{
  "length": "{{parcel_length}}",
  "width": "{{parcel_width}}",
  "height": "{{parcel_height}}",
  "distance_unit": "{{distance_unit}}",
  "weight": "{{parcel_weight}}",
  "mass_unit": "{{mass_unit}}",
  "template": "{{parcel_template}}",
  "metadata": "{{parcel_metadata}}"
}

### SHIPPO - GET ALL PARCELS

GET {{api_base_url}}/parcels/
Authorization: ShippoToken {{shippo_token}}


##############################################################################################
##############################################################################################
#############################    SHIPMENTS (To get rates)    #################################
##############################################################################################
##############################################################################################

# Variables pour l'adresse d'expédition (FROM)
@from_name = Galerie InRealArt
@from_street1 = 62 rue des forges
@from_street2 = 
@from_city = Plélan-le-grand
@from_state = Bretagne
@from_zip = 35380
@from_country = FR

# Variables pour l'adresse de destination (TO) - Paris
@to_name = Martin Dupont
@to_street1 = 25 Rue de Rivoli
@to_street2 = Appartement 4B
@to_city = Paris
@to_state = Île-de-France
@to_zip = 75004
@to_country = FR

### SHIPPO - CREATE SHIPMENT (GET RATES)

POST {{api_base_url}}/shipments/
Content-Type: {{content_type}}
Authorization: ShippoToken {{shippo_token}}

{
  "address_from": {
    "name": "{{from_name}}",
    "street1": "{{from_street1}}",
    "street2": "{{from_street2}}",
    "city": "{{from_city}}",
    "state": "{{from_state}}",
    "zip": "{{from_zip}}",
    "country": "{{from_country}}"
  },
  "address_to": {
    "name": "{{to_name}}",
    "street1": "{{to_street1}}",
    "street2": "{{to_street2}}",
    "city": "{{to_city}}",
    "state": "{{to_state}}",
    "zip": "{{to_zip}}",
    "country": "{{to_country}}"
  },
  "parcels": [{
    "length": "{{parcel_length}}",
    "width": "{{parcel_width}}",
    "height": "{{parcel_height}}",
    "distance_unit": "{{distance_unit}}",
    "weight": "{{parcel_weight}}",
    "mass_unit": "{{mass_unit}}"
  }],
  "async": false
}
