# Variables globales pour cette requête
@baseUrl = https://api.goshippo.com
@shippoToken = {{$dotenv SHIPPO_API_KEY}}
@contentType = application/json

# Taille du tableau (petit)
@parcelLength = 40
@parcelWidth = 5
@parcelHeight = 30
@parcelWeight = 1.5

# Unités
@distanceUnit = cm
@massUnit = kg

# Adresse d'expédition (FROM)
@fromName = Galerie InRealArt
@fromStreet1 = 62 rue des forges
@fromStreet2 = 
@fromCity = Plélan-le-grand
@fromState = Bretagne
@fromZip = 35380
@fromCountry = FR

# Adresse de destination (Bordeaux)
@toName = Camille Bernard
@toStreet1 = 18 Cours du Chapeau Rouge
@toStreet2 = Étage 3
@toCity = Bordeaux
@toState = Nouvelle-Aquitaine
@toZip = 33000
@toCountry = FR

### SHIPPO - CREATE SHIPMENT BORDEAUX (GET RATES)

POST {{baseUrl}}/shipments/
Content-Type: {{contentType}}
Authorization: ShippoToken {{shippoToken}}

{
  "address_from": {
    "name": "{{fromName}}",
    "street1": "{{fromStreet1}}",
    "street2": "{{fromStreet2}}",
    "city": "{{fromCity}}",
    "state": "{{fromState}}",
    "zip": "{{fromZip}}",
    "country": "{{fromCountry}}"
  },
  "address_to": {
    "name": "{{toName}}",
    "street1": "{{toStreet1}}",
    "street2": "{{toStreet2}}",
    "city": "{{toCity}}",
    "state": "{{toState}}",
    "zip": "{{toZip}}",
    "country": "{{toCountry}}"
  },
  "parcels": [{
    "length": "{{parcelLength}}",
    "width": "{{parcelWidth}}",
    "height": "{{parcelHeight}}",
    "distance_unit": "{{distanceUnit}}",
    "weight": "{{parcelWeight}}",
    "mass_unit": "{{massUnit}}"
  }],
  "async": false
} 